### PR TITLE
Fix issue with build step

### LINKED ISSUE #69: The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version. Update the npm package '@cap-js/notifications/lib/build' to the latest version.
Hi team, 
With the latest version of notifications plugin, I am getting the following error: 
```
The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version.
 Update the npm package '@cap-js/notifications/lib/build' to the latest version.
```
My cds version is 
| incident-management    | <Add your repository here>                                                                                     |
| ---------------------- | -------------------------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                                          |
| @cap-js/cds-types      | 0.6.5                                                                                                          |
| @cap-js/db-service     | 1.12.0                                                                                                         |
| @cap-js/hana           | 1.2.0                                                                                                          |
| @cap-js/notifications  | 0.2.1                                                                                                          |
| @cap-js/openapi        | 1.0.5                                                                                                          |
| @cap-js/sqlite         | 1.7.3                                                                                                          |
| @sap/cds               | 8.2.1                                                                                                          |
| @sap/cds-compiler      | 5.1.2                                                                                                          |
| @sap/cds-dk            | 8.2.0                                                                                                          |
| @sap/cds-dk (global)   | 8.2.0                                                                                                          |
| @sap/cds-fiori         | 1.2.7                                                                                                          |
| @sap/cds-foss          | 5.0.1                                                                                                          |
| @sap/cds-mtxs          | 2.1.0                                                                                                          |
| @sap/eslint-plugin-cds | 3.0.4                                                                                                          |
| Node.js                | v20.16.0                                                                                                       |

### PR DESCRIPTION
**Pull request by schiwekM**
Closes #69 

Use the new way for initialising build plugins to avoid errors during build.

BR,
Marten

### CODE REVIEW

**Review by LotharBender — APPROVED** [review]
Seems that I overlooked this plugin when searching for plugins using the outdated plugin API - thanks!

**Comment by gopalanand333** [comment]
@schiwekM @LotharBender 
I am still getting this error on running:  
```cds build --production                                                 
The cds build plugin 'notifications' is not compatible with this @sap/cds-dk version. Update the npm package '@cap-js/notifications/lib/build' to the latest version.
```
Is the fix released with newer version of notifications plugin?

**Comment by LotharBender** [comment]
@chgeo - version `0.2.2` of the `@cap-js/notifications` package has not been published yet on npmjs - can you trigger this?

**Comment by RamIndia** [comment]
@simeonPetkov96 @dzhurdzhina @nvvalchev Can you take it forward?

**Comment by niklasvieth** [comment]
Any update on releasing of the new version? #71 seems to be the same issue

**Comment by LotharBender** [comment]
@RamIndia @chgeo - is this plugin no longer maintained?

**Comment by yusmenrashidov** [comment]
Hi,
We are still working on the fix/
Regards,
Yusmen

**Comment by yusmenrashidov** [comment]
Hello there,
We have released the new version (0.2.2) where the fix is now applied.
Regards,
Yusmen

**Pull request merged**
